// File: firebase_options.dart
// *** REPLACE THIS FILE AFTER RUNNING `flutterfire configure` ***
//
// This file is normally generated by the FlutterFire CLI:
//   flutterfire configure --project=brialyns-art-sign-services
// That command overwrites this file with the real `DefaultFirebaseOptions`
// for your Firebase project. Until you run it, the values below are
// placeholders and the app will refuse to start (the error screen in
// `main.dart` will explain what to do).
//
// Do NOT commit the real file with private API keys; `flutterfire configure`
// adds the right entries to `.gitignore` automatically.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate the real values.',
        );
    }
  }

  // PLACEHOLDER VALUES — replace via `flutterfire configure`.
  // Project: brialyns-art-sign-services

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCos6j5BQD7VMgIzE6LCgkNdu3PBghE3Bg',
    appId: '1:1071186942670:web:8f6eef41064b134c850e9f',
    messagingSenderId: '1071186942670',
    projectId: 'brialyns-art-sign-services',
    authDomain: 'brialyns-art-sign-services.firebaseapp.com',
    storageBucket: 'brialyns-art-sign-services.firebasestorage.app',
    measurementId: 'G-ML74KSS9LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJSl4QZuVEtTssN3xTybPjcSwshTEfT84',
    appId: '1:1071186942670:android:cbb4a4654d809ec3850e9f',
    messagingSenderId: '1071186942670',
    projectId: 'brialyns-art-sign-services',
    storageBucket: 'brialyns-art-sign-services.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'brialyns-art-sign-services',
    iosBundleId: 'com.printflow.printflowMobile',
    storageBucket: 'brialyns-art-sign-services.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'brialyns-art-sign-services',
    iosBundleId: 'com.printflow.printflowMobile',
    storageBucket: 'brialyns-art-sign-services.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'brialyns-art-sign-services',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'brialyns-art-sign-services',
  );
}
