import '../models/order.dart';
import '../models/inventory_item.dart';
import '../models/rfid_event.dart';

/// Centralized mock data for PrintFlow Mobile app
/// Used for frontend-only demo and testing

// Helper function to generate dates relative to today
DateTime _daysAgo(int days) => DateTime.now().subtract(Duration(days: days));
DateTime _daysFromNow(int days) => DateTime.now().add(Duration(days: days));

/// Mock Orders - 12 realistic print shop orders with varied statuses
final List<Order> mockOrders = [
  // Overdue orders
  Order(
    orderId: 'PF-2026-001',
    customerName: 'Maria Santos',
    customerEmail: 'maria.santos@example.com',
    customerPhone: '+63 917 123 4567',
    itemType: 'Tarpaulin - Medium',
    quantity: 2,
    layoutFile: 'layout_uploaded.png',
    targetDate: _daysAgo(3),
    paymentAmount: 3500,
    paymentStatus: 'Partial',
    status: 'In Production',
    priority: 'Overdue',
    estimatedCompletion: _daysFromNow(1),
    basedOn: ['backlog', 'job_complexity'],
    createdAt: _daysAgo(10),
  ),
  Order(
    orderId: 'ORD-1024',
    customerName: 'Juan Dela Cruz',
    customerEmail: 'juan.delacruz@example.com',
    customerPhone: '+63 918 234 5678',
    itemType: 'T-shirt Printing',
    quantity: 50,
    layoutFile: 'design_final.jpg',
    targetDate: _daysAgo(2),
    paymentAmount: 8000,
    paymentStatus: 'Unpaid',
    status: 'Pending',
    priority: 'Overdue',
    estimatedCompletion: _daysFromNow(2),
    basedOn: ['capacity', 'backlog'],
    createdAt: _daysAgo(8),
  ),
  Order(
    orderId: 'ORD-1025',
    customerName: 'Ana Reyes',
    customerEmail: 'ana.reyes@example.com',
    customerPhone: '+63 919 345 6789',
    itemType: 'Invitation - Matte',
    quantity: 100,
    layoutFile: 'artwork.pdf',
    targetDate: _daysAgo(1),
    paymentAmount: 1200,
    paymentStatus: 'Paid',
    status: 'Ready for Pickup',
    priority: 'Overdue',
    estimatedCompletion: _daysAgo(1),
    basedOn: ['job_complexity'],
    createdAt: _daysAgo(5),
  ),

  // Urgent orders
  Order(
    orderId: 'PF-2026-002',
    customerName: 'Pedro Garcia',
    customerEmail: 'pedro.garcia@example.com',
    customerPhone: '+63 920 456 7890',
    itemType: 'Tarpaulin - Large',
    quantity: 1,
    layoutFile: 'banner_design.png',
    targetDate: DateTime.now(),
    paymentAmount: 5000,
    paymentStatus: 'Paid',
    status: 'In Production',
    priority: 'Urgent',
    estimatedCompletion: _daysFromNow(1),
    basedOn: ['backlog', 'capacity'],
    createdAt: _daysAgo(3),
  ),
  Order(
    orderId: 'ORD-1026',
    customerName: 'Rosa Mendoza',
    customerEmail: 'rosa.mendoza@example.com',
    customerPhone: '+63 921 567 8901',
    itemType: 'Mug - White 11oz',
    quantity: 20,
    layoutFile: 'mug_layout.jpg',
    targetDate: _daysFromNow(1),
    paymentAmount: 1500,
    paymentStatus: 'Paid',
    status: 'In Production',
    priority: 'Urgent',
    estimatedCompletion: _daysFromNow(2),
    basedOn: ['job_complexity', 'capacity'],
    createdAt: _daysAgo(2),
  ),
  Order(
    orderId: 'ORD-1027',
    customerName: 'Carlos Rivera',
    customerEmail: 'carlos.rivera@example.com',
    customerPhone: '+63 922 678 9012',
    itemType: 'Paper - A4 80gsm',
    quantity: 500,
    layoutFile: 'flyer_design.pdf',
    targetDate: _daysFromNow(1),
    paymentAmount: 2500,
    paymentStatus: 'Partial',
    status: 'Pending',
    priority: 'Urgent',
    estimatedCompletion: _daysFromNow(3),
    basedOn: ['backlog'],
    createdAt: _daysAgo(1),
  ),
  Order(
    orderId: 'PF-2026-003',
    customerName: 'Elena Cruz',
    customerEmail: 'elena.cruz@example.com',
    customerPhone: '+63 923 789 0123',
    itemType: 'Screen Print - Shirt Blank',
    quantity: 10,
    layoutFile: 'screen_artwork.png',
    targetDate: _daysFromNow(2),
    paymentAmount: 1500,
    paymentStatus: 'Unpaid',
    status: 'Pending',
    priority: 'Urgent',
    estimatedCompletion: _daysFromNow(4),
    basedOn: ['capacity', 'job_complexity'],
    createdAt: _daysAgo(1),
  ),

  // Upcoming orders
  Order(
    orderId: 'ORD-1028',
    customerName: 'Miguel Torres',
    customerEmail: 'miguel.torres@example.com',
    customerPhone: '+63 924 890 1234',
    itemType: 'T-shirt Printing',
    quantity: 100,
    layoutFile: 'event_shirt.jpg',
    targetDate: _daysFromNow(5),
    paymentAmount: 15000,
    paymentStatus: 'Paid',
    status: 'Pending',
    priority: 'Upcoming',
    estimatedCompletion: _daysFromNow(7),
    basedOn: ['backlog', 'capacity'],
    createdAt: DateTime.now(),
  ),
  Order(
    orderId: 'ORD-1029',
    customerName: 'Sofia Gonzales',
    customerEmail: 'sofia.gonzales@example.com',
    customerPhone: '+63 925 901 2345',
    itemType: 'Tarpaulin - Small',
    quantity: 5,
    layoutFile: 'small_banner.png',
    targetDate: _daysFromNow(7),
    paymentAmount: 2000,
    paymentStatus: 'Unpaid',
    status: 'Pending',
    priority: 'Upcoming',
    estimatedCompletion: _daysFromNow(9),
    basedOn: ['backlog'],
    createdAt: DateTime.now(),
  ),
  Order(
    orderId: 'PF-2026-004',
    customerName: 'Diego Hernandez',
    customerEmail: 'diego.hernandez@example.com',
    customerPhone: '+63 926 012 3456',
    itemType: 'Invitation - Matte',
    quantity: 200,
    layoutFile: 'wedding_invite.pdf',
    targetDate: _daysFromNow(10),
    paymentAmount: 2400,
    paymentStatus: 'Paid',
    status: 'Pending',
    priority: 'Upcoming',
    estimatedCompletion: _daysFromNow(12),
    basedOn: ['capacity', 'job_complexity'],
    createdAt: DateTime.now(),
  ),
  Order(
    orderId: 'ORD-1030',
    customerName: 'Carmen Diaz',
    customerEmail: 'carmen.diaz@example.com',
    customerPhone: '+63 927 123 4567',
    itemType: 'Mug - White 11oz',
    quantity: 10,
    layoutFile: 'corporate_mug.jpg',
    targetDate: _daysFromNow(8),
    paymentAmount: 750,
    paymentStatus: 'Partial',
    status: 'Pending',
    priority: 'Upcoming',
    estimatedCompletion: _daysFromNow(10),
    basedOn: ['backlog'],
    createdAt: DateTime.now(),
  ),
  Order(
    orderId: 'ORD-1031',
    customerName: 'Antonio Morales',
    customerEmail: 'antonio.morales@example.com',
    customerPhone: '+63 928 234 5678',
    itemType: 'Paper - A4 80gsm',
    quantity: 1000,
    layoutFile: 'brochure_final.pdf',
    targetDate: _daysFromNow(14),
    paymentAmount: 5000,
    paymentStatus: 'Paid',
    status: 'Completed',
    priority: 'Upcoming',
    estimatedCompletion: _daysFromNow(16),
    basedOn: ['capacity'],
    createdAt: _daysAgo(20),
  ),
];

/// Mock Inventory - 10 material variants with realistic stock levels
final List<InventoryItem> mockInventory = [
  // In Stock items
  InventoryItem(
    materialVariantId: 'INV-1001',
    itemType: 'T-shirt Printing',
    category: 'Apparel',
    tagUid: '04A3B2C1',
    sensorId: 'ESP32-01',
    currentStock: 200,
    threshold: 50,
    reorderPoint: 75,
    forecastedDemandNext7Days: 50,
    model: 'Holt-Winters',
    status: 'In Stock',
    isStale: false,
    lastUpdated: _daysAgo(1),
    lastCheckoutAt: _daysAgo(2),
  ),
  InventoryItem(
    materialVariantId: 'INV-1002',
    itemType: 'Tarpaulin - Medium',
    category: 'Signage',
    tagUid: '04B5D3E2',
    sensorId: 'ESP32-01',
    currentStock: 100,
    threshold: 20,
    reorderPoint: 30,
    forecastedDemandNext7Days: 10,
    model: 'Exponential Smoothing',
    status: 'In Stock',
    isStale: false,
    lastUpdated: DateTime.now(),
    lastCheckoutAt: _daysAgo(1),
  ),
  InventoryItem(
    materialVariantId: 'INV-1003',
    itemType: 'Paper - A4 80gsm',
    category: 'Paper',
    tagUid: '04C7F4A3',
    sensorId: 'ESP32-02',
    currentStock: 500,
    threshold: 100,
    reorderPoint: 150,
    forecastedDemandNext7Days: 100,
    model: 'Holt-Winters',
    status: 'In Stock',
    isStale: false,
    lastUpdated: _daysAgo(1),
    lastCheckoutAt: DateTime.now(),
  ),
  InventoryItem(
    materialVariantId: 'INV-1004',
    itemType: 'Mug - White 11oz',
    category: 'Drinkware',
    tagUid: '04D8E5B4',
    sensorId: 'ESP32-02',
    currentStock: 150,
    threshold: 30,
    reorderPoint: 50,
    forecastedDemandNext7Days: 25,
    model: 'Exponential Smoothing',
    status: 'In Stock',
    isStale: false,
    lastUpdated: DateTime.now(),
    lastCheckoutAt: _daysAgo(3),
  ),
  InventoryItem(
    materialVariantId: 'INV-1005',
    itemType: 'Invitation - Matte',
    category: 'Stationery',
    tagUid: '04E9A6C5',
    sensorId: 'ESP32-01',
    currentStock: 300,
    threshold: 50,
    reorderPoint: 100,
    forecastedDemandNext7Days: 50,
    model: 'Holt-Winters',
    status: 'In Stock',
    isStale: false,
    lastUpdated: _daysAgo(2),
    lastCheckoutAt: _daysAgo(5),
  ),

  // Low Stock items
  InventoryItem(
    materialVariantId: 'INV-1006',
    itemType: 'Tarpaulin - Large',
    category: 'Signage',
    tagUid: '04F1B7D6',
    sensorId: 'ESP32-02',
    currentStock: 30,
    threshold: 20,
    reorderPoint: 40,
    forecastedDemandNext7Days: 15,
    model: 'Exponential Smoothing',
    status: 'Low Stock',
    isStale: false,
    lastUpdated: DateTime.now(),
    lastCheckoutAt: _daysAgo(1),
  ),
  InventoryItem(
    materialVariantId: 'INV-1007',
    itemType: 'Screen Print - Shirt Blank',
    category: 'Screen Print',
    tagUid: '04A2C8E7',
    sensorId: 'ESP32-01',
    currentStock: 45,
    threshold: 30,
    reorderPoint: 50,
    forecastedDemandNext7Days: 20,
    model: 'Holt-Winters',
    status: 'Low Stock',
    isStale: true,
    lastUpdated: _daysAgo(5),
    lastCheckoutAt: _daysAgo(10),
  ),
  InventoryItem(
    materialVariantId: 'INV-1008',
    itemType: 'Tarpaulin - Small',
    category: 'Signage',
    tagUid: '04B3D9A8',
    sensorId: 'ESP32-02',
    currentStock: 25,
    threshold: 15,
    reorderPoint: 30,
    forecastedDemandNext7Days: 10,
    model: 'Exponential Smoothing',
    status: 'Low Stock',
    isStale: false,
    lastUpdated: DateTime.now(),
    lastCheckoutAt: _daysAgo(2),
  ),

  // Insufficient Stock items
  InventoryItem(
    materialVariantId: 'INV-1009',
    itemType: 'T-shirt Printing',
    category: 'Apparel',
    tagUid: null,
    sensorId: null,
    currentStock: 15,
    threshold: 50,
    reorderPoint: 75,
    forecastedDemandNext7Days: 35,
    model: 'Holt-Winters',
    status: 'Insufficient Stock',
    isStale: true,
    lastUpdated: _daysAgo(7),
    lastCheckoutAt: _daysAgo(8),
  ),
  InventoryItem(
    materialVariantId: 'INV-1010',
    itemType: 'Mug - White 11oz',
    category: 'Drinkware',
    tagUid: '04C4E1B9',
    sensorId: 'ESP32-01',
    currentStock: 10,
    threshold: 30,
    reorderPoint: 50,
    forecastedDemandNext7Days: 25,
    model: 'Exponential Smoothing',
    status: 'Insufficient Stock',
    isStale: true,
    lastUpdated: _daysAgo(3),
    lastCheckoutAt: null,
  ),
];

/// Mock RFID Activity - 15 recent checkout events
final List<RfidCheckoutEvent> mockActivity = [
  RfidCheckoutEvent(
    materialVariantId: 'INV-1001',
    tagUid: '04A3B2C1',
    sensorId: 'ESP32-01',
    timestamp: DateTime.now().subtract(const Duration(hours: 2)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1003',
    tagUid: '04C7F4A3',
    sensorId: 'ESP32-02',
    timestamp: DateTime.now().subtract(const Duration(hours: 3)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1002',
    tagUid: '04B5D3E2',
    sensorId: 'ESP32-01',
    timestamp: DateTime.now().subtract(const Duration(hours: 5)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1006',
    tagUid: '04F1B7D6',
    sensorId: 'ESP32-02',
    timestamp: DateTime.now().subtract(const Duration(hours: 6)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1004',
    tagUid: '04D8E5B4',
    sensorId: 'ESP32-02',
    timestamp: DateTime.now().subtract(const Duration(hours: 8)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1008',
    tagUid: '04B3D9A8',
    sensorId: 'ESP32-02',
    timestamp: DateTime.now().subtract(const Duration(hours: 10)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1001',
    tagUid: '04A3B2C1',
    sensorId: 'ESP32-01',
    timestamp: DateTime.now().subtract(const Duration(hours: 12)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1005',
    tagUid: '04E9A6C5',
    sensorId: 'ESP32-01',
    timestamp: DateTime.now().subtract(const Duration(hours: 14)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1007',
    tagUid: '04A2C8E7',
    sensorId: 'ESP32-01',
    timestamp: DateTime.now().subtract(const Duration(hours: 15)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1003',
    tagUid: '04C7F4A3',
    sensorId: 'ESP32-02',
    timestamp: DateTime.now().subtract(const Duration(hours: 16)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1010',
    tagUid: '04C4E1B9',
    sensorId: 'ESP32-01',
    timestamp: DateTime.now().subtract(const Duration(hours: 18)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1002',
    tagUid: '04B5D3E2',
    sensorId: 'ESP32-01',
    timestamp: DateTime.now().subtract(const Duration(hours: 19)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1006',
    tagUid: '04F1B7D6',
    sensorId: 'ESP32-02',
    timestamp: DateTime.now().subtract(const Duration(hours: 20)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1001',
    tagUid: '04A3B2C1',
    sensorId: 'ESP32-01',
    timestamp: DateTime.now().subtract(const Duration(hours: 22)),
  ),
  RfidCheckoutEvent(
    materialVariantId: 'INV-1004',
    tagUid: '04D8E5B4',
    sensorId: 'ESP32-02',
    timestamp: DateTime.now().subtract(const Duration(hours: 24)),
  ),
];

/// Mock KPIs by role
Map<String, dynamic> mockKpis(String role) {
  switch (role.toLowerCase()) {
    case 'cashier':
      return {
        'todayOrders': 12,
        'pending': 5,
        'collected': 8400.0,
        'avgPrepTime': 2.5,
      };
    case 'production':
      return {
        'overdue': 3,
        'inProduction': 4,
        'ready': 2,
        'completed': 8,
      };
    default:
      return {};
  }
}

/// Mock Customers - 8 frequent customers
final List<Map<String, dynamic>> mockCustomers = [
  {
    'name': 'Maria Santos',
    'email': 'maria.santos@example.com',
    'phone': '+63 917 123 4567',
    'lastOrder': '2026-08-18',
    'totalSpent': 12500.0,
  },
  {
    'name': 'Juan Dela Cruz',
    'email': 'juan.delacruz@example.com',
    'phone': '+63 918 234 5678',
    'lastOrder': '2026-08-20',
    'totalSpent': 8000.0,
  },
  {
    'name': 'Ana Reyes',
    'email': 'ana.reyes@example.com',
    'phone': '+63 919 345 6789',
    'lastOrder': '2026-08-23',
    'totalSpent': 5600.0,
  },
  {
    'name': 'Pedro Garcia',
    'email': 'pedro.garcia@example.com',
    'phone': '+63 920 456 7890',
    'lastOrder': '2026-08-25',
    'totalSpent': 15000.0,
  },
  {
    'name': 'Rosa Mendoza',
    'email': 'rosa.mendoza@example.com',
    'phone': '+63 921 567 8901',
    'lastOrder': '2026-08-26',
    'totalSpent': 3200.0,
  },
  {
    'name': 'Carlos Rivera',
    'email': 'carlos.rivera@example.com',
    'phone': '+63 922 678 9012',
    'lastOrder': '2026-08-27',
    'totalSpent': 7800.0,
  },
  {
    'name': 'Miguel Torres',
    'email': 'miguel.torres@example.com',
    'phone': '+63 924 890 1234',
    'lastOrder': '2026-08-28',
    'totalSpent': 22000.0,
  },
  {
    'name': 'Sofia Gonzales',
    'email': 'sofia.gonzales@example.com',
    'phone': '+63 925 901 2345',
    'lastOrder': '2026-08-28',
    'totalSpent': 4500.0,
  },
];
